-- AlterTable
ALTER TABLE "Call" ADD COLUMN     "clientAddress" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "hasPOA" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lastEdited" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "notes" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "postCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "success" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "summary" TEXT NOT NULL DEFAULT '';
